### PR TITLE
Make pioasm executable

### PR DESCRIPTION
**Pull request by blackketter**
Should fix https://github.com/Wiz-IO/wizio-pico/issues/63

### CODE REVIEW

**Comment by Wiz-IO** [comment]
? the pull say: Empty file.

**Comment by blackketter** [comment]
I'm not sure how GitHub handles mode changes in the web interface.  My diff appeared as:

```
diff --git a/darwin_x86_64/pioasm b/darwin_x86_64/pioasm
old mode 100644
new mode 100755
diff --git a/linux_x86_64/pioasm b/linux_x86_64/pioasm
old mode 100644
new mode 100755
```

I suspect that if you take the pull request it will work underneath.  Do you have a linux system you can test with?

**Comment by blackketter** [comment]
I can confirm that if you clone my repo the executable bits are set correctly.

**Comment by Wiz-IO** [comment]
someone to test :)

**Pull request merged**
